# Generated by Django 4.0 on 2024-07-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('business_whatsapp_no', models.CharField(blank=True, max_length=100, null=True)),
                ('business_physical_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('facebook_profile_url', models.URLField(blank=True)),
                ('twitter_profile_url', models.URLField(blank=True)),
                ('instagram_profile_url', models.URLField(blank=True)),
                ('clients_map_image', models.ImageField(blank=True, null=True, upload_to='business')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='business')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testifier_name', models.CharField(max_length=100)),
                ('testifier_category', models.CharField(blank=True, max_length=100)),
                ('testifier_image', models.ImageField(default='defsult.jpg', upload_to='info')),
                ('testimony', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Website_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='info')),
                ('banner_heading_1', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_subheading_heading_1', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_description_1', models.TextField(blank=True, null=True)),
                ('banner_heading_2', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_subheading_heading_2', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_description_2', models.TextField(blank=True, null=True)),
                ('banner_heading_3', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_subheading_heading_3', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_description_3', models.TextField(blank=True, null=True)),
                ('about_us_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('products_count', models.IntegerField(default=1)),
                ('clients_count', models.IntegerField(default=1)),
                ('patners_count', models.IntegerField(default=1)),
                ('users_count', models.IntegerField(default=1)),
                ('about_us_sub_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('about_us_description', models.TextField(blank=True, null=True)),
                ('about_us_image', models.ImageField(default='default.jpg', upload_to='info')),
                ('services_heading', models.CharField(blank=True, max_length=200)),
                ('services_sub_heading', models.CharField(blank=True, max_length=200)),
                ('services_description', models.TextField(blank=True)),
                ('who_we_are_sub_heading', models.CharField(blank=True, max_length=200)),
                ('who_we_are_description', models.TextField(blank=True)),
                ('who_we_are_image', models.ImageField(default='default.jpg', upload_to='info')),
            ],
        ),
    ]
