# Generated by Django 4.0 on 2024-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_detail',
            name='business_physical_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
