# Generated by Django 4.0 on 2024-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_business_detail_business_physical_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='info'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('Websites', 'Websites'), ('Marketing', 'Marketing'), ('Branding', 'Branding'), ('E-Commerce', 'E-Commerce'), ('Support', 'Support')], max_length=100),
        ),
    ]
